version: '3'

services:
  mongo:
    container_name: 'mongo'
    image: 'mongo:5'
    ports:
      - '27017:27017'
    volumes:
      - './mongo/db:/data/db'
      
  mongo-setup:
    image: 'mongo'
    volumes:
      - './mongo/scripts:/data/scripts'
    command:
      - '/data/scripts/setup.sh'
networks:
  default:
    driver: bridge