version: '3'

services:
  mongo:
    container_name: 'mongo'
    image: 'mongo:5'
    ports:
      - '27017:27017'
    volumes:
      - './mongo/db:/data/db'
    networks:
      - back-end
      
  mongo-setup:
    image: 'mongo'
    volumes:
      - './mongo/scripts:/data/scripts'
    command:
      - '/data/scripts/setup.sh'
    networks:
      - back-end

  back-end:
    container_name: back-end
    build:
      target: develop
      context: './service'
    command: 'npm run start:dev'
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - back-end
    volumes:
      - './service/package.json:/app/package.json:ro'
      - './service/tsconfig.json:/app/tsconfig.json:ro'
      - './service/tsconfig.build.json:/app/tsconfig.build.json:ro'
      - './service/src:/app/src'

networks:
  back-end:
    name: back-end
    driver: bridge