version: '3'

services:
  mongo:
    container_name: 'mongo'
    image: 'mongo:5'
    ports:
      - '27017:27017'
    volumes:
      - './mongo/db:/data/db'
      
  mongo-setup:
    image: 'mongo'
    volumes:
      - './mongo/scripts:/data/scripts'
    command:
      - '/data/scripts/setup.sh'
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
networks:
  default:
    driver: bridge